### ISSUE TITLE
url parameters when requesting static assets doesn't work

### ISSUE THREAD

**Issue by doughsay** [techpines/asset-rack#63]
If you add a url parameter onto a static asset url, it doesn't serve the asset.

The Font Awesome library specifies the font asset urls like this:
`http://localhost:3000/font/fontawesome-webfont.ttf?v=3.0.1`

Which doesn't seem to work when using asset rack StaticAssets.  The url
`http://localhost:3000/font/fontawesome-webfont.ttf`
works just fine however.

**Comment by techpines** [comment]
I think `v=3.01` is a cache buster.  Which means, they want you to be able to cache the file, and not have conflicts when you update the version.

Asset Rack adds the md5sum, which achieves the same end, so I think you're cool with just removing the url parameter.

With that being said, I think you're right that the "correct" functionality should be to also serve the asset with url parameters.

**Comment by doughsay** [comment]
Thanks, I did indeed just remove the parameter because I thought it really wouldn't make a difference.  The only thing that confused me a bit is a url hash on one the imported fonts.  I really don't see how any of these could have any effect on the loaded font, but I don't really know how it works under the hood.  The snippet from the fontawesome less file is:

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url('@{FontAwesomePath}/fontawesome-webfont.eot?v=3.0.1');
   src: url('@{FontAwesomePath}/fontawesome-webfont.eot?#iefix&v=3.0.1') format('embedded-opentype'),
    url('@{FontAwesomePath}/fontawesome-webfont.woff?v=3.0.1') format('woff'),
    url('@{FontAwesomePath}/fontawesome-webfont.ttf?v=3.0.1') format('truetype');
}
```

I removed them all, but haven't tested in IE.
