### ISSUE TITLE
How to refer to an image in css file with asset-rack

### ISSUE THREAD

**Issue by lewisou** [techpines/asset-rack#92]
For exmaple:

``` css
body {
    background-image: url('/bg.png')
    // i need the md5 version here
}
```
